# Python code obfuscated for Pak John - Clean Version
import base64, codecs

# Ini adalah 'inti' bot yang sudah saya amankan tanpa YouTube
magic = 'aW1wb3J0IHJlcXVlc3RzDQppbXBvcnQgc3lzDQppbXBvcnQgdGltZQ0KZnJvbSBjb2xvcmFtYSBpbXBvcnQgRm9yZSwgU3R5bGUsIGluaXQNCmZyb20gY2ZnIGltcG9ydCBjb29ja2llLCB1c2VyX2FnZW50LCBiZWFyDQoNCmluaXQoYXV0b3Jlc2V0PVRydWUpDQoNCmRlZiBiYW5uZXIoKToNCiAgICBwcmludChmIntGb3JlLllFTExPV11CQVJDQSBCRVJTSUggKFRBTlBBIFlPVVRVQkUpIikNCiAgICBwcmludChmIntGb3JlLkdSRUVOfS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIikNCg0KZGVmIGNsYWltKCk6DQogICAgaGVhZGVycyA9IHsiSG9zdCI6ICJ2aWVmYXVjZXQuY29tIiwgImF1dGhvcml6YXRpb24iOiBiZWFyLCAidXNlci1hZ2VudCI6IHVzZXJfYWdlbnQsICJjb29raWUiOiBjb29ja2llfQ0KICAgIHRyeToNCiAgICAgICAgciA9IHJlcXVlc3RzLmdldCgiaHR0cHM6Ly92aWVmYXVjZXQuY29tL2FwaS9mYXVjZXQiLCBoZWFkZXJzPWhlYWRlcnMpDQogICAgICAgIGlmIHIuc3RhdHVzX2NvZGUgPT0gMjAwOg0KICAgICAgICAgICAgcHJpbnQoZ adventuresIntGb3JlLkdSRUVOXVtTVUtTRVNdIEtsYWltIEJlcmhhc2lsISIpDQogICAgICAgIGVsc2U6DQogICAgICAgICAgICBwcmludChmIntGb3JlLlJFRF1bR0FHQUxdIENlayBDb29raWUvQmVhclIpDQogICAgZXhjZXB0Og0KICAgICAgICBwYXNzDQoNCmJhbm5lcigpDQp3aGlsZSBUcnVlOg0KICAgIGNsYWltKCkNCiAgICB0aW1lLnNsZWVwKDYwKQ=='

# Proses menjalankan kode tanpa jejak YouTube
eval(compile(base64.b64decode(magic),'<string>','exec'))
